spring:
  datasource:
    url: jdbc:h2:mem:testdb;Mode=PostgreSQL
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
  flyway:
    locations: classpath:db/h2
